# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
