# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjeEstrategico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado')], max_length=15, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('accion', models.TextField(null=True)),
                ('soporte', models.TextField(null=True)),
                ('ubicacion', models.TextField(null=True)),
                ('entidad', models.ManyToManyField(to='seguimiento.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('nivel', models.CharField(choices=[('1', 'Línea orientadora'), ('2', 'Línea estratégica'), ('3', 'Categoría'), ('4', 'Objetivo estratégico'), ('5', 'Estrategia'), ('6', 'Objetivo de la política')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('nivel', models.CharField(choices=[('1', 'Categoría de la política'), ('2', 'Estrategia'), ('3', 'Objetivo de la política'), ('4', 'Acciones recomendadas')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('nivel', models.CharField(choices=[('1', 'Objetivo de la política'), ('2', 'Acciones recomendadas'), ('3', 'Estrategia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaPublica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=30)),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('grupo', models.CharField(choices=[('1', 'Información general'), ('2', 'Recursos'), ('3', 'Población atendida')], max_length=2)),
                ('tipo_pregunta', models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('select', 'Selector'), ('textarea', 'Cuadro de texto')], max_length=10)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
                ('eje_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.EjeEstrategico')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('formulario_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.FormularioRespuesta')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Indicador')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Subprograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Formulario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subprograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Subprograma'),
        ),
        migrations.AddField(
            model_name='nivel3',
            name='politica_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.PoliticaPublica'),
        ),
        migrations.AddField(
            model_name='nivel2',
            name='politica_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.PoliticaPublica'),
        ),
        migrations.AddField(
            model_name='nivel1',
            name='politica_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.PoliticaPublica'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nivel1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel1'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nivel2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel2'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nivel3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel3'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='politica_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.PoliticaPublica'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Proyecto'),
        ),
        migrations.AddField(
            model_name='formulariorespuesta',
            name='vigencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Vigencia'),
        ),
    ]
