# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjeEstrategico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado')], max_length=15)),
                ('enviado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('entidad', models.ManyToManyField(to='seguimiento.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaPublica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=30)),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('select', 'Selector')], max_length=10)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
                ('eje_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.EjeEstrategico')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('formulario_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.FormularioRespuesta')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Indicador')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Subprograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Formulario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subprograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Subprograma'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='politica_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.PoliticaPublica'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Proyecto'),
        ),
        migrations.AddField(
            model_name='formulariorespuesta',
            name='vigencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Vigencia'),
        ),
    ]
