# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='soporte',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='formulariorespuesta',
            name='politica_publica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.PoliticaPublica'),
        ),
    ]
