# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='grupo',
            field=models.CharField(choices=[('1', 'Datos del indicador'), ('2', 'Información general'), ('3', 'Recursos'), ('4', 'Población atendida')], max_length=2),
        ),
    ]
