# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('politica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguimiento.PoliticaPublica')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Entidad')),
                ('indicador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Pregunta')),
            ],
        ),
    ]
