# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariorespuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('select', 'Selector')], max_length=10),
        ),
    ]
