# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_auto_20161217_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='accion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='soporte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='ubicacion',
            field=models.TextField(null=True),
        ),
    ]
