# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_auto_20161206_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariorespuesta',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formulariorespuesta',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Entidad'),
        ),
        migrations.AlterField(
            model_name='formulariorespuesta',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Indicador'),
        ),
    ]
