# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_auto_20161219_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='subprograma',
        ),
        migrations.RemoveField(
            model_name='formulariorespuesta',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='indicador',
            name='accion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='meta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nivel1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel1'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nivel2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel2'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nivel3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Nivel3'),
        ),
        migrations.AlterField(
            model_name='politicapublica',
            name='objetivo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='grupo',
            field=models.CharField(choices=[('1', 'Plan de desarrollo'), ('2', 'Información general'), ('3', 'Recursos'), ('4', 'Población atendida')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.AddField(
            model_name='observaciones',
            name='formulario_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.FormularioRespuesta'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.Indicador'),
        ),
    ]
