# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20161225_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel1',
            name='politica_publica',
        ),
        migrations.RemoveField(
            model_name='nivel2',
            name='politica_publica',
        ),
        migrations.RemoveField(
            model_name='nivel3',
            name='politica_publica',
        ),
    ]
