# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20161217_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='grupo',
            field=models.CharField(choices=[('1', 'Información general'), ('2', 'Recursos'), ('3', 'Población atendida')], max_length=2),
        ),
    ]
