# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_auto_20161225_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejeestrategico',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subprograma',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
